# Generated by Django 6.0.3 on 2026-06-24 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_favorite_options_alter_listenhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistmusic',
            options={'verbose_name': 'Трек в плейлисте', 'verbose_name_plural': 'Треки в плейлистах'},
        ),
    ]
